name: dopewars-text # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.6.2' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Make a fortune dealing drugs on the streets of New York...
description: |
   dopewars is a free Unix/Win32 rewrite of a game originally based on "Drug Wars" by John E. Dell. The idea of dopewars is to deal in drugs on the streets of New York, amassing a huge fortune and paying off the loan shark, while avoiding the ever-annoying police. The Unix/Win32 rewrite, as well as featuring a so-called "antique" mode which closely follows the original, introduces new features such as the ability to take part in multi-player games. dopewars aims to be highly configurable, and what you can't change in the configuration files you can change by poking around in the source, which is freely available under the terms of the GNU General Public License.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  dopewars_icon.png
title: Dopewars

apps:
  dopewars:
    command: dopewars
parts:
  dopewars:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      dopewars: build/
      dopewars.1: man/man1/

architectures:
  - build-on: amd64

