name: dopewars-text # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.6.2' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Boggle is a word game where you try to make as many words as you can
description: |
   Boggle is a word game in which players try to find as many words as they can from a grid of lettered dice, within a set time limit. It was invented by Allan Turoff and originally distributed by Parker Brothers.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  dopewars_icon.png
title: Dopewars

apps:
  dopewars:
    command: dopewars
parts:
  dopewars:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      dopewars: build/
      dopewars.1: man/man1/

architectures:
  - build-on: amd64

